### ISSUE TITLE
gpg: Can't check signature: public key not found

### ISSUE THREAD

**Issue by wbotelhos** [MurgaNikolay/chef-rvm#16]
Hi,

I couldn't automate the gpg donwload, since it will always run install RVM first.
Any way to fix it or downgrade the RVM via parameter? I couldn't find too.

Thank you.

```
 amazon-ebs: Mixlib::ShellOut::ShellCommandFailed
    amazon-ebs: ------------------------------------
    amazon-ebs: Expected process to exit with [0], but received '2'
    amazon-ebs: ---- Begin output of bash /tmp/foo20171005-1522-1kvxinq stable --auto-dotfiles --path '/home/deploy/.rvm' ----
    amazon-ebs: STDOUT: Turning on auto dotfiles mode.
    amazon-ebs: Downloading https://github.com/rvm/rvm/archive/1.29.3.tar.gz
    amazon-ebs: Downloading https://github.com/rvm/rvm/releases/download/1.29.3/1.29.3.tar.gz.asc
    amazon-ebs: Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).
    amazon-ebs:
    amazon-ebs: GPG signature verification failed for '/home/deploy/.rvm/archives/rvm-1.29.3.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.3/1.29.3.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:
    amazon-ebs:
    amazon-ebs: sudo gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    amazon-ebs:
    amazon-ebs: or if it fails:
    amazon-ebs:
    amazon-ebs: command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -
    amazon-ebs:
    amazon-ebs: the key can be compared with:
    amazon-ebs:
    amazon-ebs: https://rvm.io/mpapis.asc
    amazon-ebs: https://keybase.io/mpapis
    amazon-ebs:
    amazon-ebs: NOTE: GPG version 2.1.17 have a bug which cause failures during fetching keys from remote server. Please downgrade or upgrade to newer version (if available) or use the second method described above.
    amazon-ebs: STDERR: gpg: directory `/home/deploy/.gnupg' created
    amazon-ebs: gpg: new configuration file `/home/deploy/.gnupg/gpg.conf' created
    amazon-ebs: gpg: WARNING: options in `/home/deploy/.gnupg/gpg.conf' are not yet active during this run
    amazon-ebs: gpg: keyring `/home/deploy/.gnupg/pubring.gpg' created
    amazon-ebs: gpg: Signature made Sun 10 Sep 2017 08:59:21 PM UTC using RSA key ID BF04FF17
    amazon-ebs: gpg: Can't check signature: public key not found
    amazon-ebs: ---- End output of bash /tmp/foo20171005-1522-1kvxinq stable --auto-dotfiles --path '/home/deploy/.rvm' ----
    amazon-ebs: Ran bash /tmp/foo20171005-1522-1kvxinq stable --auto-dotfiles --path '/home/deploy/.rvm' returned 2
    amazon-ebs:
    amazon-ebs: Cookbook Trace:
    amazon-ebs: ---------------
    amazon-ebs: /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/chef_rvm/libraries/rvm_simple_environment_rvm.rb:44:in `rvm_install'
    amazon-ebs: /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/chef_rvm/resources/default.rb:13:in `block in class_from_file'
    amazon-ebs:
    amazon-ebs: Resource Declaration:
    amazon-ebs: ---------------------
    amazon-ebs: # In /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/app/recipes/rvm.rb
    amazon-ebs:
    amazon-ebs: 3: chef_rvm node['deploy']['user'] do
    amazon-ebs: 4:   rubies [version]
    amazon-ebs: 5: end
    amazon-ebs: 6:
    amazon-ebs:
    amazon-ebs: Compiled Resource:
    amazon-ebs: ------------------
    amazon-ebs: # Declared in /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/app/recipes/rvm.rb:3:in `from_file'
    amazon-ebs:
    amazon-ebs: chef_rvm("deploy") do
    amazon-ebs: action [:install]
    amazon-ebs: default_guard_interpreter :default
    amazon-ebs: declared_type :chef_rvm
    amazon-ebs: cookbook_name "app"
    amazon-ebs: recipe_name "rvm"
    amazon-ebs: rubies ["2.4.1"]
    amazon-ebs: end
    amazon-ebs:
    amazon-ebs: System Info:
    amazon-ebs: ------------
    amazon-ebs: chef_version=13.5.3
    amazon-ebs: platform=ubuntu
    amazon-ebs: platform_version=14.04
    amazon-ebs: ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
    amazon-ebs: program_name=chef-solo worker: ppid=1517;start=06:47:18;
    amazon-ebs: executable=/opt/chef/bin/chef-solo
```
